### ISSUE TITLE
无法进入睡眠

### ISSUE THREAD

**Issue by erleizh** [lyq1996/MSI-B660M-MORTAR-WIFI-HACKINTOSH#3]
无法进入睡眠，睡眠之后立马唤醒
看了下唤醒原因，`AppleACPIPlatformPower Wake reason: PWRB XDCI (User)`

我把我的键盘拔掉就可以睡眠了

而且主板上的s3、s4、s5唤醒也不能开，开了就没法关机了，关了就自动重启

**Comment by lyq1996** [comment]
建议换一个键盘
